### ISSUE TITLE
Better tutorial

### ISSUE THREAD

**Issue by bojidar-bg** [alketii/minilens#17]
A nice tutorial with text and pictures would be great

**Comment by bonyhardian** [comment]
Need tutorial too..

**Comment by bojidar-bg** [comment]
@bonyhardian Can you please explain what you mean?

**Comment by bojidar-bg** [comment]
I think this is mostly done in 1.0, but some tutorial levels are still missing help text.

**Comment by akien-mga** [comment]
IMO the tutorials are just fine. Let's reopen a more precise issue if there are still things to improve.
