### ISSUE TITLE
After pressing the retry button (with mouse), pressing space-button will instantly restart the level

### ISSUE THREAD

**Issue by fry-** [alketii/minilens#28]
Once the retry button got pressed in a Level, the space button (for planting bombs) will also restart the level instantly. You can see the bomb placed and in the same second the level starts over again. To finish this level, you have to go back to the level overview and start the level from beginning without pressing this retry-button (with mouse).
Pressing "R" for retry doesn't causes this issue.

**Comment by bojidar-bg** [comment]
The bug is there, because the texture button with the retry button gets focused and space triggers it
