### ISSUE TITLE
barrel counter increases with every played level

### ISSUE THREAD

**Issue by fry-** [alketii/minilens#33]
The new barrel counter on the top left corner increases the number of "overall barrels" with every played level. so at the beginning, everything is correct with for example 0/4, then next level has 5 barrels, it will increase to 0/9, next level has 7 barrels, increase to 0/16.
Some reset has to be done to this counter everytime when a level gets loaded.

**Comment by alketii** [comment]
well my mistake, should revert those changes so we can release beta2 today, and continue another day.
