### ISSUE TITLE
Add Bombs

### ISSUE THREAD

**Issue by alketii** [alketii/minilens#4]
Collect a bomb, detonate it near the Radioactive Barrel with "space key", run a bit so explosion wont hit you. The bomb should wait (countdown?) 2-3 seconds before explosion.

**Comment by bojidar-bg** [comment]
Maybe wait turns instead of secounds?

**Comment by alketii** [comment]
ok, turns sounds good.

**Comment by fry-** [comment]
I can think about 2 different ways to make this bomb:
Classic cartoon bomb:
http://1.bp.blogspot.com/_YmCO-ae2yqQ/TS0D_k_g1hI/AAAAAAAAAbo/C1WkHmZnGRc/s1600/1794.jpg
Modern bomb:
https://hamgear.files.wordpress.com/2013/01/bomb-alarm-clock.jpg

I tend to make it like the 2nd picture and add some counter to it showing 3,2,1,... _explosion_. The bomb would then be placed directly in front of the barrel.
What do you think?

**Comment by bojidar-bg** [comment]
@fry- Personally I like the cartoon one better.
