### ISSUE TITLE
Bug in new player animation that keeps playing old animation instead of idle animation

### ISSUE THREAD

**Issue by fry-** [alketii/minilens#40]
With the last commit I made, there is a bug now that keeps the old animation instead of playing the idle animation. All other animations seem to work when they get triggered, just the "idle" never gets played. I couldn't resolve this for now, so I still pushed because I think this is just a little thing.

The weird part is that if I print("new_anim") and then play that animation, it will show the correct animation in the print message but still won't play the idle animation.

**Comment by bojidar-bg** [comment]
Should that be closed by 31d2013cbd473846750ea9f06e6e58783f65e88d ?
