### ISSUE TITLE
Language translations

### ISSUE THREAD

**Issue by Calinou** [alketii/minilens#41]
Godot supports translations, so let's see how it works.

I don't know if language selection can be automatic (based on system language) or if you have to ask the user for language.

**Comment by bojidar-bg** [comment]
Sounds interesting

**Comment by erik90mx** [comment]
I can help with the spanish translation :)

**Comment by TeddyDD** [comment]
I can translate to polish :)

**Comment by bojidar-bg** [comment]
And I guess I should try to do it :smiley:

**Comment by Hamafa** [comment]
I'd like to contribute a german translation.

**Comment by Hamafa** [comment]
Off for holiday. I'll check back in 2 weeks if someone is interested :p

**Comment by akien-mga** [comment]
Fixed with da068b2, it's now possible to add translations (copy `shared/fr.po` and `levels/tutorial/fr.po` to your language and translated there).
