### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by Calinou** [alketii/minilens#47]
What needs to be done:
- Add touch controls.
- Make a GUI suitable for small screens.
- Publish as an APK, and possibly on [F-Droid](http://f-droid.org). Google Play costs money ($25) to publish apps on it, so it can be done last.

**Comment by bojidar-bg** [comment]
Almost done

**Comment by est31** [comment]
F-droid buildscript [here](https://gitlab.com/est/fdroiddata/commits/addminilens). Holding back a merge request to F-droid repository until release (Achieving simultaneous release for all platforms will be hard).
