### ISSUE TITLE
Comment style consistency

### ISSUE THREAD

**Issue by Calinou** [alketii/minilens#51]
When browsing Minilens' code, I sometimes see these variants of comments:

``` GDScript
#example comment
#Example comment
# example comment
# Example comment
```

We should settle on one style. I personally suggest `# Example comment` for comments, and `#commented_out_code` for code that was commented out (note the lack of space between the # and the code).

Typos are also quite frequent.

**Comment by bojidar-bg** [comment]
@Calinou  sorry, I wrote all comments in a hurry, so typos and variations are common...

**Comment by akien-mga** [comment]
I think the Python convention is a good one to follow: https://www.python.org/dev/peps/pep-0008/#comments
