### ISSUE TITLE
strange lines visible on acid tile

### ISSUE THREAD

**Issue by TeddyDD** [alketii/minilens#59]
Visible only on fullscreen (my screen resolution is 1600x900)
![zrzut ekranu z 2015-05-01 13 47 02](https://cloud.githubusercontent.com/assets/4397533/7429816/e117c4f4-f008-11e4-9dd6-14f2fe133785.png)

**Comment by bojidar-bg** [comment]
It this issue still present?

**Comment by TeddyDD** [comment]
Its ok now. Sorry I forgot to close this :)
