### ISSUE TITLE
Tutorial: show that barrels can collect flowers

### ISSUE THREAD

**Issue by akien-mga** [alketii/minilens#64]
As pointed out by a player on the Godot forum [1], it's not straight-forward in the first level of "First Contact" that you can collect one of the two flowers next to the bottom platform by pushing a barrel over it.

It might be a good idea to add a tutorial level about this concept, or add this concept in an existing tutorial level.

[1] http://www.godotengine.org/forum/viewtopic.php?f=8&t=1858&start=20#p9314

**Comment by alketii** [comment]
Yes this is really needed, couple of people requested it.

**Comment by akien-mga** [comment]
For the reference: fixed in 4ade7df.
@bojidar-bg You can name github tickets in commit logs, like "Fixes #64" would have made a reference and closed this issue automatically ;)

**Comment by bojidar-bg** [comment]
@akien-mga I know I can do it, but sometimes I forget to check all issues before committing, to see which are fixed.
