### ISSUE TITLE
Android movement improvements

### ISSUE THREAD

**Issue by akien-mga** [alketii/minilens#69]
While playing Minilens on a relatively wide Android tablet, I noticed two things that could probably be improved to have a better control of the robot:
- The movement pad is currently on the bottom right of the screen; on a wide tablet, it would be nice to be able to at least have the "left" button on the left side of the screen. Maybe "left" and "up" could be on the left, and "right", "bottom" and "bomb" on the right. There should probably be a settings to switch from "split" to "one location" keypads.
- When going up a stair (see screenshot), it's a bit bothersome to have to do right/up/right/up/right/up, etc.. When the situation is non ambiguous (i.e. a ladder next to a blocking wall), going against the wall should probably make the robot go one tile up the ladder (over the wall tile).

![minilens](https://cloud.githubusercontent.com/assets/4701338/8019773/cdb18f12-0c5f-11e5-9fb7-bef517d4496d.jpg)

**Comment by bojidar-bg** [comment]
+1 for the second idea.
About the first one, I guess I'll think a bit more about it :smile:

**Comment by alketii** [comment]
I totally agree with Akien, its counter intuitive to use navigation buttons only in one side.

**Comment by akien-mga** [comment]
Another idea that I got when playing Minilens on an Android phone (i.e. relatively small medium compared to a tablet): it would be great to be able to move left/right just by touching (and holding) the left and right side of the screen. It might also work for the up and down sides, I need to experiment to see if it's practical. Then there would only be a button for the bomb.

This system and the current one could be toggled in the options menu (as the current one is probably better on large medium where you don't hold it like a gameboy, while my new proposal would be better on phones).

I might have a look at it myself in the coming days, while testing Juan's new feature to live debug android games :)

**Comment by akien-mga** [comment]
BTW it's the first time I play Minilens for real (i.e. more than the tutorials + the 2-3 first levels), and I really like this game :-D

**Comment by akien-mga** [comment]
> it would be great to be able to move left/right just by touching (and holding) the left and right side of the screen. It might also work for the up and down sides, I need to experiment to see if it's practical. Then there would only be a button for the bomb.

I've done a quick and dirty implementation of this idea, let me know what you think of it: https://github.com/akien-mga/minilens/tree/phone_ctrl
Best tested on an android device ;)

**Comment by akien-mga** [comment]
I reintegrated and slightly improved my work from the above-linked branch: ea0b7d3
There's still room for improvement, but I'd be glad to get some feedback :)

**Comment by bojidar-bg** [comment]
@akien-mga ~ I guess we should move the touchscreenbuttons to both sides of the screen, maybe up/down + bomb on one side and left/right on the other... or maybe have a bomb button on both sides :smiley: 

Also, on widescreen tablets, it is uncomfortable to try to reach an up/down area with a thumb, so buttons are more comfortable there... except that now one thumb does all the work...

**Comment by akien-mga** [comment]
Partly done in 1.2, but there is still room for improvement (and the auto-up behaviour described above could still be a nice addition).

**Comment by ObaniGemini** [comment]
If @fry- feels the want to enhance the [current buttons](https://github.com/KOBUGE-Games/minilens/tree/master/gfx) (arrowX_STATE.png)
