### ISSUE TITLE
Asset licenses?

### ISSUE THREAD

**Issue by kozross** [alketii/minilens#70]
Are your assets also under the GNU GPL, or are they under some other license(s)?

**Comment by Calinou** [comment]
https://github.com/KOBUGE-Games/minilens/blob/master/CREDITS.txt says:

```
Kenney - http://kenney.nl - for the most graphical assets
Michel Baradari - http://opengameart.org/content/2-high-quality-explosions - for explosion sounds
Blender Foundation - http://opengameart.org/content/life-pickup-yo-frankie - for flower pickup sound
```

So, they use different (but free) licenses.

**Comment by akien-mga** [comment]
We should clarify this, with a precise listing of license and attribution for each files.
I believe there are also assets that were made by our own artists, and those need licensing and attribution too.

**Comment by bojidar-bg** [comment]
A good part (~50%) of the assets were made by @fry- , but he didn't have time to publish them on opengameart.... We will have to wait until he is back, before we can say for sure.

**Comment by bojidar-bg** [comment]
(_Late comment, sorry_)
Ok, assets are now published on [OGA](http://opengameart.org/content/minilens), and the license is CC-BY-SA 3.0.
