### ISSUE TITLE
this is not an issue, is a question

### ISSUE THREAD

**Issue by mrmrn** [alketii/minilens#72]
Hi
I see minilens in the f-droid under gpl3 licence.
And according the link I am here to see the android source.
But there is not the minilens android game source.
Can I have the minilens android version source code or its not possible?

**Comment by bojidar-bg** [comment]
@mrmrn ~ We cannot provide you with the java source-code for the android version are using the [Godot game engine](http://www.godotengine.org). Because of this, we need to store only the assets and scripts for the game, and not the whole engine source, which you can find [on GitHub](https://github.com/godotengine/godot). Note that by using a game engine, we are able to write the code once for all platforms, and by using an engine not made by us, we save enormous amounts of work.

If you mean by source-code the script files of the project, you can easily browse them in the `scripts/` directory.

**Comment by mrmrn** [comment]
Dear bojidar-bg
thank you a lot for your interesting game. I downloaded godot engine in Ubuntu and saw the game source in godot. It is very good and clean.
but I must have some study to build an android apk by godot engine.

**Comment by est31** [comment]
For building the APK, F-droid builds the godot engine from source, see here:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/io.github.kobuge.games.minilens.txt

There is also a guide on the [godot engine wiki](https://github.com/godotengine/godot/wiki/export_android) on how to export apks, it is probably more useful to you.

Note that if you publish a modified version of the minilens APK, you need to abide the GPL license, which requires you to publish sources. Adding admob and publishing it on google play is even forbidden (same goes for apple app store).

**Comment by mrmrn** [comment]
est31, thank you for your comments, nice game, nice team.

**Comment by mrmrn** [comment]
can anyone use in app-purchase for such games in google play?
for example 3 level of game is free and for others the user must pay some money

**Comment by akien-mga** [comment]
You can use IAP for such games yes, but not for Minilens, as it's an open source game under the GPLv3+ license and this license does not allow you to do this as @est31 mentioned. None of us are interested in IAP here, so you'd better ask on some official Godot channel (forum, IRC, Facebook group, etc.)

**Comment by mrmrn** [comment]
@akien-mga
I dont want to distribute minilens in Google play, I used that name as an example for knowing have it such capability to be a in app-purchases?
thank you all for your responses.

**Comment by est31** [comment]
The Godot license allows for in app-purchases, afaik, but on the how to (whether there is specific engine support for it, or whether you need to include/write a module, etc), you should ask the godot community:
- [Facebook](https://facebook.com/groups/godotengine)
- [Twitter](https://twitter.com/godotengine)
- [Reddit](https://www.reddit.com/r/godot)
- [Forum](http://godotengine.org/projects/godot-engine/boards)

This is the wrong place :)

**Comment by mrmrn** [comment]
ok, thank you alot.
really good team and nice friends for me. ;-)
