### ISSUE TITLE
Transition to .tscn

### ISSUE THREAD

**Issue by bojidar-bg** [alketii/minilens#73]
This is the new Godot engine format, that seems to gain popularity between KOBUGE-Games members, as it allows for easy preview of the data itself.

**Comment by akien-mga** [comment]
Sounds very formal :D
But yeah that's a good idea.

**Comment by 27thLiz** [comment]
That would mean it'll need godot 2.0 to run. If you do this, please remove SUTjoystick as it breaks gamepad input for 2.0

**Comment by akien-mga** [comment]
Thanks, will keep that in mind :)

**Comment by akien-mga** [comment]
Done with 79d2824 and later.
