### ISSUE TITLE
Replace SUTJoystick by native support

### ISSUE THREAD

**Issue by akien-mga** [alketii/minilens#74]
I have no clue about how SUTJoystick is used so far and how it should be replaced, but I also have troubles using my Steam Controller as a normal Xinput gamepad, so I'd be glad to have some help on this.

@Hinsbart? :D

**Comment by akien-mga** [comment]
It's also spamming the logs, time to get rid of it :D

**Comment by bojidar-bg** [comment]
It's also moving the mouse to the bottom-right corner every time `emulate_mouse` is called :cry:
