### ISSUE TITLE
Level advancement is broken on Android and HTML5

### ISSUE THREAD

**Issue by akien-mga** [alketii/minilens#75]
I had noticed this on HTML5 already, but apparently Android has the same bug: whenever you finish a level, it tells you that you finished the whole pack, and you have to go back to the menu to be able to select the next level.

**Comment by akien-mga** [comment]
The error comes from the method used to check if there are other levels, it's probably not working on Android and HTML5: https://github.com/KOBUGE-Games/minilens/blob/master/scripts/level_holder.gd#L125-L130

**Comment by akien-mga** [comment]
I've tried with `File.file_exists` instead, but it gives the same issue. I guess Android can't access the contents of `res://` with the File API?

**Comment by bojidar-bg** [comment]
@akien-mga ~ I guess that if we move https://github.com/KOBUGE-Games/minilens/blob/master/scripts/main_menu.gd#L58-L65 to a global script, it might be possible to access them from the level holder and just check with `<`/`>`

**Comment by bojidar-bg** [comment]
Should be fixed with 76d451f1f11b4a2607afd43b5a028dd4657f7ec6
