### ISSUE TITLE
Scaling issue on 1366x768 screen makes UI unusable

### ISSUE THREAD

**Issue by akien-mga** [alketii/minilens#80]
As reported in https://bugs.mageia.org/show_bug.cgi?id=18228#c6 (see the linked screencast).

**Comment by bojidar-bg** [comment]
Uh, I guess I should have tested the resize code a bit more...

**Comment by akien-mga** [comment]
I haven't managed to reproduce myself when downscaling (I found #79) instead, but it's clear from the video that there's something weird :D

**Comment by bojidar-bg** [comment]
This needs testing after ca74fb82ea53d00ff5abb5a3a2b908681f74bd21

**Comment by akien-mga** [comment]
Seems to be fixed: https://bugs.mageia.org/show_bug.cgi?id=18228#c12
