### ISSUE TITLE
ERROR: get_unique_ID: Method/Function Failed, returning: ""

### ISSUE THREAD

**Issue by akien-mga** [alketii/minilens#82]
Due to this call:

```
shared/save_manager.gd
9:      FileManager.set_file_password(save_path, str("minilens", OS.get_unique_ID())) # Set the password
```

we get:

```
ERROR: get_unique_ID: Method/Function Failed, returning: ""
   At: core/os/os.cpp:459.
```

It's probably a Godot bug, but it needs investigating.

**Comment by bojidar-bg** [comment]
@akien-mga That happens because `get_unique_ID` is implemented only on `platform/android` and `platform/ios`

**Comment by ObaniGemini** [comment]
Isn't there a way to get the platform you currently are on to fix this quickly ?

**Comment by akien-mga** [comment]
We should just drop this nonsense of trying to restrict saves to a uuid, we don't have IAPs...
