### ISSUE TITLE
how to make touch buttons appear as default.

### ISSUE THREAD

**Issue by thrishulh** [alketii/minilens#98]
how to make touch buttons appear as default instead of touch areas for controling movement of robo

**Comment by ObaniGemini** [comment]
https://github.com/KOBUGE-Games/minilens/blob/master/shared/settings_manager.gd#L12
change `input_mode` from `INPUT_AREAS` to `INPUT_BUTTONS`

**Comment by ObaniGemini** [comment]
May I ask what is this for ?

**Comment by thrishulh** [comment]
Sure looks good to play on my Mac

**Comment by thrishulh** [comment]
& one more thing it's strange on my laptop which isn't touch sensitive
display buttons are visible , I have gone through the lovely code u have
written u have masked touch controls
